import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "LandMark Estates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=" h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        </body>
    </html>
  );
}
